# Generated by Django 2.1.1 on 2023-02-06 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='listinig',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='listinig_id',
            new_name='listing_id',
        ),
    ]
